<?php
/**
 * Created by PhpStorm.
 * User: nvk3d
 * Date: 14.05.17
 * Time: 17:40
 */

namespace app\modules\main\controllers;


use app\models\Log;
use yii\web\Controller;

class ParentController extends Controller
{
    public function beforeAction($action)
    {
        Log::add($action);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}